export const NewsDataList = [
    {
        isSponsored: false,
        newsTag: "Politica",
        newsTitle:"Caldas Novas descobre que existe água fria",
        newsIntro: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
        textNews: "",
        imgNews: "/img/prive.jpg",
        timePost:" 8 horas atrás",
        newsPath:'/',
    },
    {
        isSponsored: true,
        newsTag: "Politica",
        newsTitle:"Caldas Novas descobre que existe água fria",
        newsIntro: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
        textNews: "",
        imgNews: "/img/prive.jpg",
        timePost:" 8 horas atrás",
        newsPath:'/',
    },
    {
        isSponsored: false,
        newsTag: "Politica",
        newsTitle:"Caldas Novas descobre que existe água fria",
        newsIntro: "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English.",
        textNews: "",
        imgNews: "/img/prive.jpg",
        timePost:" 8 horas atrás",
        newsPath:'/',
    },
]